apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gatewayql
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "25%"
      maxUnavailable: "25%"
  replicas: 1
  selector:
    matchLabels:
      app: gatewayql
  template: 
    metadata:  
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"              
      labels:
        app: gatewayql
    spec:            
      containers:
      - name: gatewayql        
        image: jeanlucafp/apigatewayql:1
        ports:
        - containerPort: 8080        
        env:
          - name: PORT
            value: "8080"
          - name: NODE_ENV
            value: production